import 'product_i/product_items.dart';

final List<ProductItem> productItems = [
  ProductItem(name: 'Kent 4 nazik  ', count: 0),
  ProductItem(name: 'Kent 4 qalın ', count: 0),
  ProductItem(name: 'Kent 1  ', count: 0),
  ProductItem(name: 'Kent 8  ', count: 0),
  ProductItem(name: 'Kent kompakt boz  ', count: 0),
  ProductItem(name: 'Kent kompakt göy  ', count: 0),
  ProductItem(name: 'Kent mentol  ', count: 0),
  ProductItem(name: 'Kent mentol sarı  ', count: 0),
  ProductItem(name: 'Kent sticks Classic Tobacco  ', count: 0),
  ProductItem(name: 'Kent sticks Berry Mix  ', count: 0),
  ProductItem(name: 'Winiston kompakt boz  ', count: 0),
  ProductItem(name: 'Winiston kompakt göy  ', count: 0),
  ProductItem(name: 'Winiston nazik boz  ', count: 0),
  ProductItem(name: 'Winiston nazik göy  ', count: 0),
  ProductItem(name: 'Winiston kompakt caster   ', count: 0),
  ProductItem(name: 'Sabranie qalın ag  ', count: 0),
  ProductItem(name: 'Sabranie qalın qara   ', count: 0),
  ProductItem(name: 'Sabranie qalın göy   ', count: 0),
  ProductItem(name: 'Sabranie kompakt caster  ', count: 0),
  ProductItem(name: 'Sabranie kompakt ag  ', count: 0),
  ProductItem(name: 'Sabranie kompakt qara  ', count: 0),
  ProductItem(name: 'Sabranie kompakt göy  ', count: 0),
  ProductItem(name: 'Sabranie nazik ag  ', count: 0),
  ProductItem(name: 'Sabranie nazik qara  ', count: 0),
  ProductItem(name: 'Sabranie nazik göy  ', count: 0),
  ProductItem(name: 'Sabranie nazik caster  ', count: 0),
  ProductItem(name: 'Winchester kompakt göy  ', count: 0),
  ProductItem(name: 'Winchester kompakt boz  ', count: 0),
  ProductItem(name: 'Winchester nazik göy  ', count: 0),
  ProductItem(name: 'Winchester nazik boz  ', count: 0),
  ProductItem(name: 'LD nazik boz  ', count: 0),
  ProductItem(name: 'LD kompakt ağ  ', count: 0),
  ProductItem(name: 'LD kompakt göy  ', count: 0),
  ProductItem(name: 'Davidov nazik boz   ', count: 0),
  ProductItem(name: 'Davidov nazik ağ  ', count: 0),
  ProductItem(name: 'Davidov nazik göy   ', count: 0),
  ProductItem(name: 'Davidov kompakt boz  ', count: 0),
  ProductItem(name: 'Davidov kompakt göy  ', count: 0),
  ProductItem(name: 'Davidov kompakt mentol  ', count: 0),
  ProductItem(name: 'Davidov uzun sarı  ', count: 0),
  ProductItem(name: 'Rotmons boz  ', count: 0),
  ProductItem(name: 'Rotmons göy  ', count: 0),
  ProductItem(name: 'Rotmons mentol sarı  ', count: 0),
  ProductItem(name: 'Pall mall nazik boz  ', count: 0),
  ProductItem(name: 'Pall mall nazik ağ  ', count: 0),
  ProductItem(name: 'Pall mall nazik göy  ', count: 0),
  ProductItem(name: 'Pall mall nazik mentol  ', count: 0),
  ProductItem(name: 'Pall mall qalın göy  ', count: 0),
  ProductItem(name: 'Pall mall qalın boz  ', count: 0),
  ProductItem(name: 'Viceroy boz  ', count: 0),
  ProductItem(name: 'Viceroy göy   ', count: 0),
  ProductItem(name: 'Viceroy ağ   ', count: 0),
  ProductItem(name: 'West qalın  ', count: 0),
  ProductItem(name: 'West kompakt boz  ', count: 0),
  ProductItem(name: 'Magna kompakt boz  ', count: 0),
  ProductItem(name: 'Magna kompakt göy  ', count: 0),
  ProductItem(name: 'Magna nazik boz   ', count: 0),
  ProductItem(name: 'Magna nazik qara   ', count: 0),
  ProductItem(name: 'Magna ağ  ', count: 0),
  ProductItem(name: 'Want nazik boz  ', count: 0),
  ProductItem(name: 'Want nazik qara  ', count: 0),
  ProductItem(name: 'Want nazik göy  ', count: 0),
  ProductItem(name: 'Want LX nazik ağ  ', count: 0),
  ProductItem(name: 'Want LX nazik göy  ', count: 0),
  ProductItem(name: 'Want LX nazik qırmızı  ', count: 0),
  ProductItem(name: 'Want LX kompkat qırmızı  ', count: 0),
  ProductItem(name: 'Want LX kompakt göy  ', count: 0),
  ProductItem(name: 'Want Lx nazik mentol  ', count: 0),
  ProductItem(name: 'Want Lx kompakt mentol  ', count: 0),
  ProductItem(name: 'Classic kompakt boz  ', count: 0),
  ProductItem(name: 'Classic kompakt göy  ', count: 0),
  ProductItem(name: 'Classic nazik göy  ', count: 0),
  ProductItem(name: 'Kingston qalın boz  ', count: 0),
  ProductItem(name: 'Kingston qalın qızılı  ', count: 0),
  ProductItem(name: 'Kingston nazik göy  ', count: 0),
  ProductItem(name: 'Kingston nazik qırmızı  ', count: 0),
  ProductItem(name: 'Veqas boz  ', count: 0),
  ProductItem(name: 'Veqas göy  ', count: 0),
  ProductItem(name: 'Veqas qalın boz  ', count: 0),
  ProductItem(name: 'Arqo qalın göy  ', count: 0),
  ProductItem(name: 'Arqo qalın qırmızı  ', count: 0),
  ProductItem(name: 'Arqo nazik göy  ', count: 0),
  ProductItem(name: 'Arqo nazik qırmızı  ', count: 0),
  ProductItem(name: 'Arqo nazik ağ caster  ', count: 0),
  ProductItem(name: 'Arqo kompakt göy  ', count: 0),
  ProductItem(name: 'Arqo kompakt qırmızı  ', count: 0),
  ProductItem(name: 'Prima göy  ', count: 0),
  ProductItem(name: 'Bakı göy  ', count: 0),
  ProductItem(name: 'Bakı qara  ', count: 0),
  ProductItem(name: 'Qarabağ qara  ', count: 0),
  ProductItem(name: 'Qarabağ ağ  ', count: 0),
  ProductItem(name: 'Keno nazik Platinum  ', count: 0),
  ProductItem(name: 'Keno nazik Royal  ', count: 0),
  ProductItem(name: 'Keno nazik Night  ', count: 0),
  ProductItem(name: 'Keno nazik mentol Gum Mint  ', count: 0),
  ProductItem(name: 'Keno nazik mentol Orange  ', count: 0),
  ProductItem(name: 'Keno nazik mentol Grape  ', count: 0),
  ProductItem(name: 'Keno kompakt göy  ', count: 0),
  ProductItem(name: 'Keno kompakt qırmızı   ', count: 0),
  ProductItem(name: 'Neo kompakt Bright Tabacco  ', count: 0),
  ProductItem(name: 'Neo kompakt Redberry Pastel  ', count: 0),
  ProductItem(name: 'Neo kompakt Brilliant Berry  ', count: 0),
  ProductItem(name: 'Neo kompakt Melon Boost  ', count: 0),
  ProductItem(name: 'Neo kompakt Terracotto Tabacco  ', count: 0),
  ProductItem(name: 'Neo nazik Boost Scarlet  ', count: 0),
  ProductItem(name: 'Neo nazik Boost Red ', count: 0),
  ProductItem(name: 'Neo nazik Rich Tabacco ', count: 0),
  ProductItem(name: 'Qazlı su 0.5 ', count: 0),
  ProductItem(name: 'Qazsız su 0.5 ', count: 0),
  ProductItem(name: 'Kola 0.3  ', count: 0),
  ProductItem(name: 'Kola 0.5  ', count: 0),
  ProductItem(name: 'Kola 1 L.  ', count: 0),
  ProductItem(name: 'Kola 2 L.  ', count: 0),
  ProductItem(name: 'Kola dəmir banka.', count: 0),
  ProductItem(name: 'Fanta 0.3  ', count: 0),
  ProductItem(name: 'Fanta 0.5  ', count: 0),
  ProductItem(name: 'Fanta 1 L.  ', count: 0),
  ProductItem(name: 'Fanta 2 L.  ', count: 0),
  ProductItem(name: 'Cappy Şaftalı 0.5', count: 0),
  ProductItem(name: 'Cappy Portağal 0.5', count: 0),
  ProductItem(name: 'Cappy Qarışıq 0.5', count: 0),
  ProductItem(name: 'Cappy Albalı 0.5', count: 0),
  ProductItem(name: 'Fuse-Tea Şaftalı 0.5', count: 0),
  ProductItem(name: 'Fuse-Tea Limon 0.5', count: 0),
  ProductItem(name: 'Fuse-Tea Mango-Ananas  0.5', count: 0),
  ProductItem(name: 'Fuse-Tea Mango-Çobanyastığı  0.5', count: 0),
  ProductItem(name: 'Fuse-Tea Şaftalı 0.5', count: 0),
  ProductItem(name: 'Fuse-Tea Şaftalı 300ml.', count: 0),
  ProductItem(name: 'Fuse-Tea Limon 300ml.', count: 0),
  ProductItem(name: 'Fuse-Tea Mango-Ananas 300ml.', count: 0),
  ProductItem(name: 'Çöplü sok Qarışıq.', count: 0),
  ProductItem(name: 'Çöplü sok Şaftalı.', count: 0),
  ProductItem(name: 'RedBull 250ml.', count: 0),
  ProductItem(name: 'Hell qırmızı 250ml.', count: 0),
  ProductItem(name: 'Hell qara 250ml.', count: 0),
  ProductItem(name: 'Hell qırmızı 250ml.', count: 0),
  ProductItem(name: 'Bizon balaca qırmızı.', count: 0),
  ProductItem(name: 'Bizon böyük qırmızı.', count: 0),
  ProductItem(name: 'Bizon balaca göy.', count: 0),
  ProductItem(name: 'Bizon böyük göy.', count: 0),
  ProductItem(name: 'Maxito 250ml.', count: 0),
  ProductItem(name: 'LaimonFresh 330ml.', count: 0),
  ProductItem(name: 'MacCoffee 240ml.', count: 0),
  ProductItem(name: 'Berq 250ml.', count: 0),
  ProductItem(name: 'Berq tea Mango 0.5', count: 0),
  ProductItem(name: 'Fruiting 238ml.', count: 0),
  ProductItem(name: 'Sarı kız sadə.', count: 0),
  ProductItem(name: 'Sarı kız Limonlı.', count: 0),
  ProductItem(name: 'Full balaca göy', count: 0),
  ProductItem(name: 'Full böyük göy', count: 0),
  ProductItem(name: 'Full tea Albalı 0.5', count: 0),
  ProductItem(name: 'Full tea Mango-Ananas 0.5 ', count: 0),
  ProductItem(name: 'Full tea Giləmeyvə 0.5 ', count: 0),
  ProductItem(name: 'Full tea Saftalı 0.5 ', count: 0),
  ProductItem(name: 'Xırdalan banka. ', count: 0),
  ProductItem(name: 'Xırdalan butulka. ', count: 0),
  ProductItem(name: 'Go qara. ', count: 0),
  ProductItem(name: 'Go sarı. ', count: 0),
  ProductItem(name: 'Kuller. ', count: 0),
  ProductItem(name: 'Baltika 9 . ', count: 0),
  ProductItem(name: 'Yaquar. ', count: 0),
  ProductItem(name: 'Romanov araq ', count: 0),
];
